-- Migration 028: XHTTP client transport profile on vpn_keys.
--
-- This project applies migrations programmatically from db/database.py
-- (schema_version bumped to 28, see Database._migrate_v28). This file documents
-- migration 028 as a standalone, reviewable artifact and is kept in sync with
-- both _migrate_v28 and db/schema.sql. The number is the next one in sequence
-- after the existing schema version (27 -> 28).
--
-- Adds xhttp_profile: 'base' | 'antisib' | 'multi'. Meaningful only for http
-- (vless-xhttp-reality) keys; tcp/AWG/legacy rows stay 'base'. NOT NULL DEFAULT
-- 'base' backfills every existing row. Idempotent: _migrate_v28 only runs the
-- ALTER when the column is absent. Mirrors the baseline declaration in
-- db/schema.sql (re-ensured on every bootstrap).
--
-- NOTE: _migrate_v28 has a SECOND, data-only step with no DDL equivalent here:
-- it rewrites Xray email_label values into the transport/profile-aware scheme
-- (xray_tcp_<rnd> / xray_http_base_<rnd>) and patches the stored display_name /
-- link copies (_relabel_xray_emails_v28). UUIDs (client identity) are never
-- touched. That transform is code-only and intentionally not reproduced as SQL.

ALTER TABLE vpn_keys ADD COLUMN xhttp_profile TEXT NOT NULL DEFAULT 'base';
