-- Schema snapshot: version 33. GENERATED by scripts/dump_schema_snapshot.py —
-- do not hand-edit. Replayed by tests/test_schema_upgrade_path.py, which loads this
-- file into an empty database, stamps schema_version=33 and runs bootstrap()
-- to prove the upgrade path from this version still works.

PRAGMA foreign_keys = ON;

CREATE TABLE access_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  telegram_user_id INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  username TEXT,
  status TEXT NOT NULL CHECK(status IN ('pending','approved','rejected')),
  requested_at TEXT NOT NULL,
  -- decided_by intentionally has NO FK (legacy actor ids may predate the users
  -- table); orphans are validated at bootstrap by _validate_reference_integrity.
  decided_by INTEGER,
  decided_at TEXT,
  decision_note TEXT
);

CREATE TABLE announcement_batches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  actor_user_id INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE RESTRICT,
  from_chat_id INTEGER NOT NULL,
  message_id INTEGER NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('pending','sending','completed','failed','cancelled','scheduled')),
  total_count INTEGER NOT NULL DEFAULT 0,
  success_count INTEGER NOT NULL DEFAULT 0,
  failed_count INTEGER NOT NULL DEFAULT 0,
  skipped_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  completed_at TEXT,
  scheduled_at TEXT,
  -- Segmentation filter (roles/protocols/transports as JSON) for targeted
  -- broadcasts; NULL means an unsegmented "send to all" batch. Mirrors _migrate_v27.
  recipient_filter_json TEXT
);

CREATE TABLE announcement_deliveries (
  announcement_id INTEGER NOT NULL REFERENCES announcement_batches(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK(status IN ('pending','sent','failed','skipped')),
  error_text TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (announcement_id, user_id)
);

CREATE TABLE audit_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  actor_user_id INTEGER,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  details_json TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE deleted_key_traffic_archive (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key_id INTEGER NOT NULL,
  owner_user_id INTEGER NOT NULL,
  key_type TEXT NOT NULL,
  downloaded_bytes INTEGER NOT NULL DEFAULT 0,
  uploaded_bytes INTEGER NOT NULL DEFAULT 0,
  deleted_at TEXT NOT NULL
);

CREATE TABLE key_bundles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  label TEXT NOT NULL UNIQUE,
  note TEXT,
  status TEXT NOT NULL CHECK(status IN ('active','pending_revoke','revoked','pending_delete','delete_failed','deleted')),
  -- Secret embedded in the subscription sub-URL. Stored in plain text on purpose,
  -- consistent with how the child keys' vless uuid / hy2 auth already live in this
  -- table, and because the "Config" button must be able to re-render the sub-URL
  -- later. UNIQUE so a token maps to exactly one bundle. Mirrors _migrate_v32.
  token TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  revoked_at TEXT,
  deleted_at TEXT,
  -- The number shown to the user as «All-in-One #N», reserved out of the vpn_keys
  -- id space so bundles and keys share ONE running count (see
  -- VpnKeyRepository.reserve_display_number). Without it `id` restarted at 1 and
  -- the first subscription read «#1» next to keys numbered «#176».
  -- Nullable only because ADD COLUMN cannot add a NOT NULL column without a
  -- constant default; _migrate_v33 backfills every existing row and the
  -- repository always writes it, so NULL never survives a bootstrap.
  display_no INTEGER
);

CREATE TABLE maintenance_settings (
  id         INTEGER PRIMARY KEY DEFAULT 1,
  enabled    INTEGER NOT NULL DEFAULT 0,
  message    TEXT,
  started_at INTEGER NOT NULL DEFAULT 0,
  started_by INTEGER,
  updated_at INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE protocol_modules (
    name        TEXT PRIMARY KEY,
    enabled     INTEGER NOT NULL DEFAULT 1,
    disabled_at TEXT,
    disabled_by INTEGER REFERENCES users(telegram_user_id) ON DELETE SET NULL
);

CREATE TABLE proxy_accesses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_user_id INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  username TEXT,
  access_type TEXT NOT NULL CHECK(access_type IN ('socks5','mtproto')),
  status TEXT NOT NULL CHECK(status IN (
    'pending_apply','active','apply_failed','pending_revoke','revoked','revoke_failed','inactive',
    'pending_delete','delete_failed','deleted'
  )),
  secret_fingerprint TEXT,
  apply_generation INTEGER NOT NULL DEFAULT 0,
  payload_json TEXT NOT NULL,
  public_payload_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  activated_at TEXT,
  last_apply_at TEXT,
  last_shown_at TEXT,
  revoked_at TEXT,
  deleted_at TEXT,
  created_by INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE RESTRICT,
  revoked_by INTEGER REFERENCES users(telegram_user_id) ON DELETE SET NULL,
  deleted_by INTEGER REFERENCES users(telegram_user_id) ON DELETE SET NULL,
  reason TEXT,
  error TEXT
);

CREATE TABLE proxy_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  proxy_type TEXT NOT NULL CHECK(proxy_type IN ('socks5','socks4','http','https')),
  host TEXT NOT NULL,
  port INTEGER NOT NULL,
  login TEXT,
  password TEXT,
  note TEXT,
  status TEXT NOT NULL CHECK(status IN ('active','disabled')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE schema_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE server_status_settings (
  id               INTEGER PRIMARY KEY DEFAULT 1,
  detailed_enabled INTEGER NOT NULL DEFAULT 0,
  updated_at       INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE trial_key_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  telegram_user_id INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  key_type TEXT NOT NULL CHECK(key_type IN ('xray','awg')),
  status TEXT NOT NULL CHECK(status IN ('pending','approved','rejected')),
  key_id INTEGER REFERENCES vpn_keys(id) ON DELETE SET NULL,
  requested_at TEXT NOT NULL,
  decided_by INTEGER REFERENCES users(telegram_user_id) ON DELETE SET NULL,
  decided_at TEXT
);

CREATE TABLE "users" (
                  telegram_user_id INTEGER PRIMARY KEY,
                  username TEXT,
                  first_name TEXT,
                  role TEXT NOT NULL CHECK(role IN ('SUPERADMIN','MODERATOR','APPROVED_USER','PENDING_USER','BLOCKED_USER')),
                  created_at TEXT NOT NULL,
                  updated_at TEXT NOT NULL,
                  blocked_at TEXT,
                  trial_quota_reset_at TEXT DEFAULT NULL,
                  note TEXT DEFAULT NULL
                , language TEXT DEFAULT NULL, expiry_notifications_enabled INTEGER NOT NULL DEFAULT 1);

CREATE TABLE vpn_key_traffic_stats (
  key_id INTEGER PRIMARY KEY,
  downloaded_bytes INTEGER NOT NULL DEFAULT 0,
  uploaded_bytes INTEGER NOT NULL DEFAULT 0,
  last_raw_downloaded_bytes INTEGER,
  last_raw_uploaded_bytes INTEGER,
  last_success_at TEXT,
  last_attempt_at TEXT,
  available INTEGER NOT NULL DEFAULT 0,
  unavailable_reason TEXT,
  source TEXT,
  FOREIGN KEY(key_id) REFERENCES vpn_keys(id) ON DELETE CASCADE
);

CREATE TABLE vpn_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_user_id INTEGER NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
  username TEXT,
  key_type TEXT NOT NULL CHECK(key_type IN ('xray','awg','hysteria2')),
  status TEXT NOT NULL CHECK(status IN ('pending_apply','active','apply_failed','pending_revoke','revoked','pending_delete','delete_failed','deleted','failed')),
  note TEXT,
  uuid TEXT,
  email_label TEXT,
  public_key TEXT,
  client_ip TEXT,
  payload_json TEXT NOT NULL,
  public_payload_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  revoked_at TEXT,
  expires_at TEXT DEFAULT NULL,
  expiry_notified_days TEXT DEFAULT NULL,
  -- VLESS transport: 'tcp' (vless-in) or 'http' (vless-xhttp-reality). Always
  -- 'tcp' for AWG keys and pre-XHTTP legacy rows. Mirrors _migrate_v23.
  transport TEXT NOT NULL DEFAULT 'tcp',
  -- XHTTP client transport profile: 'base' | 'antisib' | 'multi'. Meaningful only
  -- for http keys; 'base' for tcp/AWG keys and legacy rows. Mirrors _migrate_v28.
  xhttp_profile TEXT NOT NULL DEFAULT 'base',
  -- Per-key REALITY spiderX (spx) emitted into the VLESS client link. NULL means
  -- spx is not emitted (default, full backward compat). Client-side only: never
  -- written to the server inbound. Nullable by design. Mirrors _migrate_v31.
  spider_x TEXT,
  deleted_at TEXT,
  -- created_by/revoked_by/deleted_by intentionally have NO foreign key (unlike
  -- proxy_accesses): users are NEVER hard-deleted (only blocked via role), so
  -- these actor references cannot dangle in practice. owner_user_id keeps its
  -- ON DELETE CASCADE. If a hard-delete path for users is ever added, these
  -- columns must be handled (otherwise _validate_reference_integrity fails at
  -- the next bootstrap on created_by, which is validated as non-nullable).
  created_by INTEGER NOT NULL,
  revoked_by INTEGER,
  deleted_by INTEGER,
  -- All-in-one subscription bundle this key belongs to. NULL = standalone key
  -- (the default and every pre-v32 row). ON DELETE RESTRICT is deliberate: a
  -- bundle can never be deleted while a child key still points at it — PR-2's
  -- service must first revoke the backend credentials and clear/delete the
  -- children, and only then the bundle row. CASCADE would silently drop the
  -- children and leave orphaned Xray/hysteria credentials behind. Mirrors
  -- _migrate_v32.
  bundle_id INTEGER REFERENCES key_bundles(id) ON DELETE RESTRICT
);

CREATE TABLE warp_settings (
  id              INTEGER PRIMARY KEY DEFAULT 1,
  enabled         INTEGER NOT NULL DEFAULT 0,
  config_path     TEXT    NOT NULL DEFAULT '/etc/amnezia/out-warp.conf',
  interface_name  TEXT    NOT NULL DEFAULT 'out-warp',
  routes_count    INTEGER NOT NULL DEFAULT 0,
  tunnel_up       INTEGER NOT NULL DEFAULT 0,
  routes_active   INTEGER NOT NULL DEFAULT 0,
  fail_streak     INTEGER NOT NULL DEFAULT 0,
  success_streak  INTEGER NOT NULL DEFAULT 0,
  last_handshake  INTEGER NOT NULL DEFAULT 0,
  last_check_ts   INTEGER NOT NULL DEFAULT 0,
  kill_switch     INTEGER NOT NULL DEFAULT 0,
  config_installed INTEGER NOT NULL DEFAULT 0,
  updated_at      INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_access_requests_one_pending
                ON access_requests(telegram_user_id)
                WHERE status = 'pending';

CREATE INDEX idx_access_requests_pending_created
                ON access_requests(status, requested_at);

CREATE INDEX idx_access_requests_user_status ON access_requests(telegram_user_id, status);

CREATE INDEX idx_announcement_batches_scheduled ON announcement_batches(scheduled_at) WHERE status = 'scheduled' AND scheduled_at IS NOT NULL;

CREATE INDEX idx_announcement_batches_status ON announcement_batches(status, updated_at);

CREATE INDEX idx_announcement_deliveries_status ON announcement_deliveries(announcement_id, status, user_id);

CREATE INDEX idx_audit_log_created_at ON audit_log(created_at);

CREATE INDEX idx_audit_log_entity ON audit_log(entity_type, entity_id, created_at);

CREATE INDEX idx_deleted_key_traffic_archive_owner ON deleted_key_traffic_archive(owner_user_id, downloaded_bytes, uploaded_bytes);

CREATE INDEX idx_deleted_key_traffic_archive_type ON deleted_key_traffic_archive(key_type, downloaded_bytes, uploaded_bytes);

CREATE UNIQUE INDEX idx_key_bundles_display_no ON key_bundles(display_no);

CREATE INDEX idx_key_bundles_status ON key_bundles(status);

CREATE INDEX idx_key_bundles_user_id ON key_bundles(user_id);

CREATE INDEX idx_proxy_accesses_login ON proxy_accesses(json_extract(payload_json, '$.login')) WHERE access_type = 'socks5';

CREATE INDEX idx_proxy_accesses_mtproto_fingerprint ON proxy_accesses(secret_fingerprint) WHERE access_type = 'mtproto' AND secret_fingerprint IS NOT NULL;

CREATE UNIQUE INDEX idx_proxy_accesses_one_live_per_user_type
            ON proxy_accesses(owner_user_id, access_type)
            WHERE status IN ('pending_apply','active','pending_revoke');

CREATE INDEX idx_proxy_accesses_owner ON proxy_accesses(owner_user_id);

CREATE INDEX idx_proxy_accesses_owner_type_status ON proxy_accesses(owner_user_id, access_type, status);

CREATE INDEX idx_proxy_accesses_status_type ON proxy_accesses(status, access_type);

CREATE UNIQUE INDEX idx_trial_requests_one_pending
            ON trial_key_requests(telegram_user_id)
            WHERE status = 'pending';

CREATE INDEX idx_trial_requests_user ON trial_key_requests(telegram_user_id, status);

CREATE INDEX idx_users_active_role ON users(role) WHERE blocked_at IS NULL;

CREATE INDEX idx_users_role ON users(role);

CREATE INDEX idx_vpn_key_traffic_stats_success ON vpn_key_traffic_stats(last_success_at);

CREATE INDEX idx_vpn_keys_bundle_id ON vpn_keys(bundle_id) WHERE bundle_id IS NOT NULL;

CREATE UNIQUE INDEX idx_vpn_keys_client_ip_reserved
                ON vpn_keys(client_ip)
                WHERE client_ip IS NOT NULL
                  AND key_type = 'awg'
                  AND status IN ('pending_apply','active','apply_failed','pending_revoke','pending_delete','delete_failed');

CREATE UNIQUE INDEX idx_vpn_keys_email_label ON vpn_keys(email_label) WHERE email_label IS NOT NULL;

CREATE INDEX idx_vpn_keys_expires_at ON vpn_keys(expires_at) WHERE expires_at IS NOT NULL AND status = 'active';

CREATE INDEX idx_vpn_keys_owner ON vpn_keys(owner_user_id);

CREATE INDEX idx_vpn_keys_owner_type_status ON vpn_keys(owner_user_id, key_type, status);

CREATE UNIQUE INDEX idx_vpn_keys_public_key ON vpn_keys(public_key) WHERE public_key IS NOT NULL;

CREATE INDEX idx_vpn_keys_short_id ON vpn_keys(json_extract(payload_json, '$.short_id')) WHERE key_type = 'xray' AND json_valid(payload_json) AND json_extract(payload_json, '$.short_id') IS NOT NULL;

CREATE INDEX idx_vpn_keys_status_type
                ON vpn_keys(status, key_type);

CREATE INDEX idx_vpn_keys_type_status ON vpn_keys(key_type, status);

CREATE UNIQUE INDEX idx_vpn_keys_uuid ON vpn_keys(uuid) WHERE uuid IS NOT NULL;
