#!/usr/bin/env python3
"""Dump the live schema of a freshly bootstrapped DB as a versioned snapshot.

The snapshots under ``tests/schema_snapshots/`` are the fixtures the upgrade
harness (``tests/test_schema_upgrade_path.py``) replays: it materialises an OLD
database from ``vNN.sql``, runs ``Database.bootstrap()`` on it and asserts the
result is indistinguishable from a fresh bootstrap. Without a snapshot of the
version currently in production, nothing in CI ever executes the upgrade path —
which is how a baseline DDL statement referencing a migration-added column
(``key_bundles.display_no``) shipped green twice and crash-looped the bot on a
live v32 database.

Workflow when adding a migration:

    1. On the tree that still has the OLD ``CURRENT_SCHEMA_VERSION`` (i.e. before
       your bump lands), run::

           python scripts/dump_schema_snapshot.py

       It writes ``tests/schema_snapshots/v<OLD>.sql``.
    2. Optionally hand-write ``tests/schema_snapshots/v<OLD>.seed.sql`` with a few
       rows, so the harness also exercises the backfill your migration does.
    3. Bump ``CURRENT_SCHEMA_VERSION``, write the migration, run pytest. The
       harness now upgrades the snapshot to the new version on every CI run.

``test_previous_version_snapshot_exists`` fails the build when step 1 is
forgotten, so the ladder cannot silently develop a hole.

The output is the DDL of every user object in ``sqlite_master`` (tables first,
then indexes, each sorted by name), which is exactly what ``sqlite3 .schema``
would print, minus the SQLite-internal ``sqlite_*`` objects that cannot be
recreated by DDL (``sqlite_sequence`` reappears on its own as soon as an
AUTOINCREMENT table is created).
"""

from __future__ import annotations

import argparse
import asyncio
import sqlite3
import sys
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from db.database import CURRENT_SCHEMA_VERSION, Database  # noqa: E402


HEADER = """\
-- Schema snapshot: version {version}. GENERATED by scripts/dump_schema_snapshot.py —
-- do not hand-edit. Replayed by tests/test_schema_upgrade_path.py, which loads this
-- file into an empty database, stamps schema_version={version} and runs bootstrap()
-- to prove the upgrade path from this version still works.
"""


async def _dump() -> str:
    with tempfile.TemporaryDirectory() as tmp:
        db = Database(Path(tmp) / "snapshot.db")
        await db.connect()
        try:
            await db.bootstrap()
            rows = await db.conn.execute_fetchall(
                "SELECT type, name, sql FROM sqlite_master "
                "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' "
                "ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name"
            )
        finally:
            await db.close()
    statements = [str(row["sql"]).strip() for row in rows]
    body = ";\n\n".join(statements)
    return HEADER.format(version=CURRENT_SCHEMA_VERSION) + "\nPRAGMA foreign_keys = ON;\n\n" + body + ";\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="destination file (default: tests/schema_snapshots/v<CURRENT_SCHEMA_VERSION>.sql)",
    )
    args = parser.parse_args()
    output: Path = args.output or (REPO_ROOT / "tests" / "schema_snapshots" / f"v{CURRENT_SCHEMA_VERSION}.sql")

    dump = asyncio.run(_dump())
    # Fail loudly instead of writing a snapshot that cannot be replayed.
    probe = sqlite3.connect(":memory:")
    try:
        probe.executescript(dump)
    finally:
        probe.close()

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(dump, encoding="utf-8")
    print(f"wrote {output} (schema_version={CURRENT_SCHEMA_VERSION})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
